### PR TITLE
fix: restore hints when unauthorized

### LINKED ISSUE #315: Restore hints when unauthorized
#255 added helpful hints to tell the user what to do if `dbc install <private-driver>` errors:

> Did you run `dbc auth login`?

> Do you have an active license for this driver? Contact support@columnar.tech for assistance.

These were lost in the refactor in #279. Restore them.

### PR DESCRIPTION
**Pull request by zeroshade**
## Summary
Restores helpful hints that were lost in the error handling refactor (#279):
- Added hint for `ErrUnauthorized`: "Did you run `dbc auth login`?"
- Restored simpler hint for `ErrUnauthorizedColumnar` with original wording from #255

## Context
These hints were originally added in #255 to help users troubleshoot authorization issues when installing private drivers. During the error handling refactor in #279, these hints were either removed or changed to more verbose messages.

## Changes
- `cmd/dbc/main.go`: Updated `formatErr()` function to include both helpful hints

Fixes #315

### CODE REVIEW

File: cmd/dbc/main.go [hunk 1]
```diff
@@ -153,10 +153,11 @@ func formatErr(err error) string {
 	case errors.Is(err, auth.ErrNoTrialLicense):
 		return errStyle.Render("Could not download license, trial not started")
 	case errors.Is(err, dbc.ErrUnauthorized):
-		return errStyle.Render(err.Error())
+		return errStyle.Render(err.Error()) + "\n" +
+			msgStyle.Render("Did you run `dbc auth login`?")
 	case errors.Is(err, dbc.ErrUnauthorizedColumnar):
 		return errStyle.Render(err.Error()) + "\n" +
-			msgStyle.Render("Installing this driver requires a license. Verify you have an active license at https://console.columnar.tech/licenses and try this command again. Contact support@columnar.tech if you believe this is an error.")
+			msgStyle.Render("Do you have an active license for this driver? Contact support@columnar.tech for assistance.")
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply cmd/dbc/main.go]: @copilot open a new pull request to apply changes based on [this feedback](https://github.com/columnar-tech/dbc/pull/321#discussion_r2834741562)

Comment (amoeba) [inline cmd/dbc/main.go]: Was reverting this improvement to the error message intended here?

Comment (zeroshade) [reply cmd/dbc/main.go]: that's a good point and my mistake there. The current version of this is better, i'll fix that
