### PR TITLE
fix(installing): use a '-' instead of check when using --no-verify

### LINKED ISSUE #305: Installing with --no-verify still uses a green checkmark for verifying step
```sh
$ go run ./cmd/dbc install --no-verify some_driver_unsigned_fixed.tar.gz
Installing from local package: some_driver_unsigned_fixed.tar.gz

[✓] installing
[✓] verifying signature

Installed some_driver_unsigned_fixed 1.10.0 to /Users/bryce/Library/Application Support/ADBC/Drivers
```

I think the `✓` should be a `-` or something to indicate the step was skipped.

### PR DESCRIPTION
**Pull request by zeroshade**
fixes #305

### CODE REVIEW

File: cmd/dbc/install.go [hunk 1]
```diff
@@ -415,6 +415,10 @@ func checkbox(label string, checked bool) string {
 
 var postMsgStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("3"))
 
+var (
+	skipMark = lipgloss.NewStyle().Foreground(lipgloss.Color("3")).SetString("-")
```
Comment (amoeba) [inline cmd/dbc/install.go]: Maybe merge this with the definition of `checkMark` in sync.go?
